"""Visual asset schemas. Domain- and provider-independent.

Chain: a VisualPlan lists VisualRequirements -> each fulfilled requirement becomes one IMAGE_ASSET artifact
(an ImageAsset) -> whose attribution records where the image came from: the external source of a searched
image, or the provider, model and prompt hash of a generated one. Attribution is copied from providers by
code, never written by a model, and it is separate from the lesson's textual citation chain
(Citation -> Evidence -> Source): an image is never evidence.
"""

from __future__ import annotations

import re
from datetime import datetime
from enum import Enum
from typing import Annotated, Literal

from pydantic import Field, field_validator, model_validator

from app.schemas.artifact import Artifact, StoredObject
from app.schemas.common import Schema

# --- Visual types ---------------------------------------------------------------------------


class VisualType(str, Enum):
    """What kind of picture a visual is. Add members as new kinds are needed; nothing is subject-specific."""

    PHOTO = "photo"
    ILLUSTRATION = "illustration"
    DIAGRAM = "diagram"
    CHART = "chart"
    MAP = "map"
    ICON = "icon"
    GENERATED_VISUAL = "generated_visual"

    @classmethod
    def parse(cls, value: str | None) -> VisualType | None:
        """Map a provider's label to a visual type; None when it names nothing we know."""
        if not value:
            return None
        key = value.strip().lower().replace("-", "_").replace(" ", "_")
        aliases = {"photograph": "photo", "image": "photo", "drawing": "illustration", "vector": "illustration",
                   "clipart": "illustration", "graph": "chart", "figure": "diagram"}
        try:
            return cls(aliases.get(key, key))
        except ValueError:
            return None


# Real-world depictions must come from a real source: a generated "photo" or "map" would mislead learners.
SEARCH_ONLY = frozenset({VisualType.PHOTO, VisualType.MAP})
GENERATE_ONLY = frozenset({VisualType.GENERATED_VISUAL})

VisualSource = Literal["search", "generate"]
ImageOrigin = Literal["search", "generated"]

ASPECT_RATIO = re.compile(r"^([1-9]\d?):([1-9]\d?)$")
URL_LIKE = re.compile(r"(https?://|www\.|data:\w+/|file://)", re.IGNORECASE)
ASPECT_TOLERANCE = 0.02  # relative difference allowed between an image's ratio and the expected one


def aspect_value(ratio: str) -> float:
    match = ASPECT_RATIO.match(ratio)
    if not match:
        raise ValueError(f"aspect ratio must look like '16:9', got {ratio!r}")
    return int(match.group(1)) / int(match.group(2))


def aspect_matches(width: int, height: int, ratio: str, tolerance: float = ASPECT_TOLERANCE) -> bool:
    expected = aspect_value(ratio)
    return abs(width / height - expected) / expected <= tolerance


# --- Visual planning ------------------------------------------------------------------------


class VisualRequirement(Schema):
    visual_id: str = Field(pattern=r"^[A-Za-z0-9_.-]{1,64}$")
    purpose: str = Field(min_length=1)
    lesson_section_id: str
    concept: str = Field(min_length=1)
    description: str = Field(min_length=1)  # what the image shows; also its alt text
    visual_type: VisualType
    preferred_source: VisualSource
    search_query: str | None = None
    generation_prompt: str | None = None
    aspect_ratio: str = "16:9"
    required: bool = True
    attribution_required: bool = True

    @field_validator("aspect_ratio")
    @classmethod
    def _ratio(cls, value: str) -> str:
        aspect_value(value)
        return value

    @model_validator(mode="after")
    def _consistent(self) -> VisualRequirement:
        for name in ("purpose", "concept", "description", "search_query", "generation_prompt"):
            value = getattr(self, name)
            if value and URL_LIKE.search(value):
                raise ValueError(f"{name} must not contain a URL; images are found or generated by tools")
        if self.preferred_source == "search" and not (self.search_query or "").strip():
            raise ValueError(f"visual {self.visual_id}: a searched visual needs a search_query")
        if self.preferred_source == "generate" and not (self.generation_prompt or "").strip():
            raise ValueError(f"visual {self.visual_id}: a generated visual needs a generation_prompt")
        if self.visual_type in SEARCH_ONLY and self.preferred_source != "search":
            raise ValueError(f"visual {self.visual_id}: a {self.visual_type.value} must be searched, not generated")
        if self.visual_type in GENERATE_ONLY and self.preferred_source != "generate":
            raise ValueError(f"visual {self.visual_id}: a {self.visual_type.value} must be generated")
        return self

    def sources(self) -> list[VisualSource]:
        """Where to look, in order: the preferred source, then the other one when this visual allows it."""
        order: list[VisualSource] = [self.preferred_source]
        if self.preferred_source == "search" and self.generation_prompt and self.visual_type not in SEARCH_ONLY:
            order.append("generate")
        if self.preferred_source == "generate" and self.search_query and self.visual_type not in GENERATE_ONLY:
            order.append("search")
        return order


class VisualPlanProposal(Schema):
    """What the model proposes. The system assigns the plan id and checks it against the lesson."""

    requirements: list[VisualRequirement] = Field(default_factory=list)
    rationale: str = ""

    @field_validator("requirements")
    @classmethod
    def _unique(cls, requirements: list[VisualRequirement]) -> list[VisualRequirement]:
        ids = [r.visual_id for r in requirements]
        if len(ids) != len(set(ids)):
            raise ValueError("visual ids must be unique")
        return requirements


class VisualPlan(VisualPlanProposal):
    plan_id: str
    lesson_title: str

    def requirement(self, visual_id: str) -> VisualRequirement:
        return next(r for r in self.requirements if r.visual_id == visual_id)


# --- Attribution (a metadata chain separate from textual citations) --------------------------


class ImageLicense(Schema):
    name: str = Field(min_length=1)
    url: str | None = None


class SearchAttribution(Schema):
    """Exactly what the image provider reported. Unknown fields stay None; nothing is filled in."""

    kind: Literal["search"] = "search"
    provider: str
    image_id: str
    provider_image_id: str
    image_url: str
    source_url: str  # the page the image is published on
    title: str
    creator: str | None = None
    publisher: str | None = None
    license: ImageLicense | None = None
    attribution_text: str | None = None
    retrieved_at: datetime


class GenerationAttribution(Schema):
    """Provenance of a generated image. It has no source URL: a generated image is never external evidence."""

    kind: Literal["generated"] = "generated"
    provider: str
    model: str
    generated_at: datetime
    prompt: str
    prompt_hash: str  # sha256 of the prompt as sent
    negative_prompt: str | None = None
    style: str | None = None
    seed: int | None = None
    width: int
    height: int
    ignored_parameters: list[str] = Field(default_factory=list)  # requested but unsupported by the provider
    provider_metadata: dict = Field(default_factory=dict)


VisualAttribution = Annotated[SearchAttribution | GenerationAttribution, Field(discriminator="kind")]


# --- Image search --------------------------------------------------------------------------


class ImageSearchRequest(Schema):
    query: str = Field(min_length=1)
    visual_type: VisualType | None = None
    aspect_ratio: str | None = None
    language: str | None = None
    max_results: int = Field(default=8, ge=1, le=50)


class ImageSearchResult(Schema):
    """A candidate image, normalised from any provider. Provider-only fields are kept in `metadata`."""

    image_id: str  # stable: derived from provider and provider id
    provider: str
    provider_image_id: str
    url: str
    thumbnail_url: str | None = None
    title: str
    description: str = ""
    source_url: str
    publisher: str | None = None
    creator: str | None = None
    width: int = Field(ge=1)
    height: int = Field(ge=1)
    format: str  # MIME type as reported by the provider
    license: ImageLicense | None = None
    attribution_text: str | None = None
    visual_type: VisualType | None = None  # as reported by the provider, when it maps to a known type
    source_type: str = "unknown"
    tags: list[str] = Field(default_factory=list)
    rank: int = Field(ge=1)
    retrieved_at: datetime
    metadata: dict = Field(default_factory=dict)

    def attribution(self) -> SearchAttribution:
        return SearchAttribution(
            provider=self.provider, image_id=self.image_id, provider_image_id=self.provider_image_id,
            image_url=self.url, source_url=self.source_url, title=self.title, creator=self.creator,
            publisher=self.publisher, license=self.license, attribution_text=self.attribution_text,
            retrieved_at=self.retrieved_at,
        )


class ImageUsage(Schema):
    """Deterministic usage units. `cost_usd` is set only when the provider itself reports a cost."""

    requests: int = Field(default=1, ge=0)
    results: int = Field(default=0, ge=0)
    images: int = Field(default=0, ge=0)
    megapixels: float = Field(default=0.0, ge=0)
    cost_usd: float | None = None


class ImageSearchResponse(Schema):
    request: ImageSearchRequest
    results: list[ImageSearchResult]
    provider: str
    usage: ImageUsage


class ImageFetchRequest(Schema):
    result: ImageSearchResult


class FetchedImage(Schema):
    image_id: str
    object: StoredObject


# --- Image generation ------------------------------------------------------------------------


class ImageGenerationRequest(Schema):
    prompt: str = Field(min_length=1)
    negative_prompt: str | None = None
    aspect_ratio: str | None = None
    width: int = Field(default=1280, ge=64, le=4096)
    height: int = Field(default=720, ge=64, le=4096)
    style: str | None = None
    seed: int | None = Field(default=None, ge=0)

    @model_validator(mode="after")
    def _size_matches_ratio(self) -> ImageGenerationRequest:
        if self.aspect_ratio is not None and not aspect_matches(self.width, self.height, self.aspect_ratio):
            raise ValueError(f"{self.width}x{self.height} does not have aspect ratio {self.aspect_ratio}")
        return self


class ImageGenerationResult(Schema):
    asset_id: str
    provider: str
    model: str
    width: int
    height: int
    format: str
    metadata: GenerationAttribution
    storage: StoredObject
    usage: ImageUsage


# --- Selection ------------------------------------------------------------------------------


class SelectionWeights(Schema):
    relevance: float = Field(default=0.40, ge=0)
    aspect: float = Field(default=0.20, ge=0)
    visual_type: float = Field(default=0.15, ge=0)
    license: float = Field(default=0.15, ge=0)
    source_quality: float = Field(default=0.05, ge=0)
    resolution: float = Field(default=0.05, ge=0)


class SelectionSignals(Schema):
    relevance: float = Field(ge=0, le=1)
    aspect: float = Field(ge=0, le=1)
    visual_type: float = Field(ge=0, le=1)
    license: float = Field(ge=0, le=1)
    source_quality: float = Field(ge=0, le=1)
    resolution: float = Field(ge=0, le=1)


class RankedImage(Schema):
    rank: int = Field(ge=1)
    score: float
    eligible: bool
    reasons: list[str] = Field(default_factory=list)  # why an ineligible candidate was excluded
    signals: SelectionSignals
    candidate: ImageSearchResult  # untouched, with all source metadata


class ImageSelectionRequest(Schema):
    requirement: VisualRequirement
    candidates: list[ImageSearchResult]
    weights: SelectionWeights = Field(default_factory=SelectionWeights)


class ImageSelectionResult(Schema):
    ranked: list[RankedImage]
    selector: str

    def eligible(self) -> list[RankedImage]:
        return [r for r in self.ranked if r.eligible]


# --- Validation -----------------------------------------------------------------------------

ValidationCode = Literal[
    "empty_content", "checksum_mismatch", "unreadable_image", "unsupported_format", "format_mismatch",
    "dimension_mismatch", "too_small", "too_large", "aspect_ratio_mismatch", "missing_source",
    "missing_license", "missing_attribution", "invalid_generation_metadata", "origin_mismatch",
]


class ImageValidationError(Schema):
    code: ValidationCode
    field: str
    message: str
    expected: str | None = None
    actual: str | None = None


class ImageValidationRequest(Schema):
    object: StoredObject
    declared_width: int
    declared_height: int
    declared_format: str  # MIME type
    expected_aspect_ratio: str | None = None
    attribution: VisualAttribution
    attribution_required: bool = False
    origin: ImageOrigin


class MeasuredImage(Schema):
    format: str
    media_type: str
    width: int
    height: int
    checksum: str
    size_bytes: int


class ImageValidationReport(Schema):
    valid: bool
    errors: list[ImageValidationError] = Field(default_factory=list)
    checks: list[str] = Field(default_factory=list)  # every check that ran
    measured: MeasuredImage | None = None
    validator: str

    @model_validator(mode="after")
    def _consistent(self) -> ImageValidationReport:
        if self.valid == bool(self.errors):
            raise ValueError("a report is valid exactly when it has no errors")
        return self


# --- The IMAGE_ASSET artifact ----------------------------------------------------------------


class SelectionRecord(Schema):
    selector: str
    rank: int
    score: float
    signals: SelectionSignals
    candidates: int
    rejected: list[dict] = Field(default_factory=list)  # {image_id, stage, reason}


class ImageAsset(Schema):
    """Metadata of an IMAGE_ASSET artifact. The binary lives in the object store at `object.uri`."""

    asset_id: str  # content-derived: identical bytes, identical asset id
    visual_id: str
    plan_id: str
    lesson_section_id: str
    visual_type: VisualType
    purpose: str
    description: str
    origin: ImageOrigin
    object: StoredObject
    width: int
    height: int
    format: str
    attribution: VisualAttribution
    selection: SelectionRecord | None = None
    validation: ImageValidationReport

    @model_validator(mode="after")
    def _consistent(self) -> ImageAsset:
        expected = "search" if self.origin == "search" else "generated"
        if self.attribution.kind != expected:
            raise ValueError(f"a {self.origin} image needs {expected} attribution")
        if not self.validation.valid:
            raise ValueError("an image asset must pass validation")
        if self.origin == "search" and self.selection is None:
            raise ValueError("a searched image must record how it was selected")
        return self


class ImageAssetRequest(Schema):
    name: str
    asset: ImageAsset
    attribution_required: bool
    expected_aspect_ratio: str | None = None
    parent_ids: list[str] = Field(default_factory=list)


# --- Visual agent result ----------------------------------------------------------------------


class VisualAssetRef(Schema):
    visual_id: str
    lesson_section_id: str
    artifact_id: str
    asset_id: str
    visual_type: VisualType
    origin: ImageOrigin
    purpose: str
    description: str
    uri: str
    checksum: str
    media_type: str
    width: int
    height: int


class VisualAttempt(Schema):
    source: VisualSource
    stage: Literal["search", "select", "fetch", "generate", "validate", "store"]
    message: str
    image_id: str | None = None
    errors: list[ImageValidationError] = Field(default_factory=list)


class VisualFailure(Schema):
    visual_id: str
    lesson_section_id: str
    required: bool
    reason: str
    attempts: list[VisualAttempt] = Field(default_factory=list)


class VisualResult(Schema):
    status: Literal["complete", "partial", "failed"]  # failed: a required visual could not be produced
    plan: VisualPlan
    plan_artifact_id: str
    artifacts: list[Artifact] = Field(default_factory=list)  # the VISUAL_PLAN, then every IMAGE_ASSET
    assets: list[VisualAssetRef] = Field(default_factory=list)
    failures: list[VisualFailure] = Field(default_factory=list)
    warnings: list[str] = Field(default_factory=list)

    @model_validator(mode="after")
    def _consistent(self) -> VisualResult:
        planned = {r.visual_id for r in self.plan.requirements}
        done = [a.visual_id for a in self.assets]
        failed = [f.visual_id for f in self.failures]
        if len(done) != len(set(done)) or set(done) & set(failed) or (set(done) | set(failed)) != planned:
            raise ValueError("every planned visual is either an asset or a failure, once")
        if {a.artifact_id for a in self.artifacts} != {self.plan_artifact_id} | {a.artifact_id for a in self.assets}:
            raise ValueError("artifacts must be the visual plan and the image assets")
        expected = ("failed" if any(f.required for f in self.failures)
                    else "partial" if self.failures else "complete")
        if self.status != expected:
            raise ValueError(f"status must be '{expected}'")
        return self

    def for_section(self, section_id: str) -> list[VisualAssetRef]:
        return [a for a in self.assets if a.lesson_section_id == section_id]
