"""Media tools (image, narration audio, video). Results are stored as artifacts so agents never
handle files or URLs directly. Not used by the text-lesson workflow yet."""

from __future__ import annotations

from pydantic import Field

from app.artifacts.service import ArtifactService
from app.observability.scope import ExecutionScope
from app.providers.image.base import ImageProvider
from app.providers.tts.base import TTSProvider
from app.providers.video.base import SceneSpec, VideoProvider
from app.schemas.artifact import Artifact, ArtifactType
from app.schemas.common import Schema
from app.tools.base import Tool, ToolError


def _require_task(scope: ExecutionScope) -> str:
    if scope.task_id is None:
        raise ToolError("media artifacts can only be created inside a task")
    return scope.task_id


class ImageInput(Schema):
    name: str
    prompt: str = Field(min_length=1)
    width: int = Field(default=1280, ge=64, le=4096)
    height: int = Field(default=720, ge=64, le=4096)
    parent_ids: list[str] = Field(default_factory=list)


class ImageGenerationTool(Tool[ImageInput, Artifact]):
    name = "image.generate"
    description = "Generate an image and store it as an IMAGE artifact (identical prompts are reused)."
    input_model = ImageInput
    output_model = Artifact
    permissions = frozenset({"media:generate", "artifact:write"})

    def __init__(self, provider: ImageProvider, artifacts: ArtifactService) -> None:
        self._provider = provider
        self._artifacts = artifacts

    async def run(self, data: ImageInput, scope: ExecutionScope) -> Artifact:
        image = await self._provider.generate(data.prompt, data.width, data.height)
        return self._artifacts.store(
            task_id=_require_task(scope), name=data.name, type=ArtifactType.IMAGE, media_type=image.media_type,
            content=image.content, provider=image.provider, parent_ids=data.parent_ids,
            metadata={**image.metadata, "attribution": f"generated by {image.provider}"}, scope=scope,
        )


class SpeechInput(Schema):
    name: str
    text: str = Field(min_length=1)
    voice: str = "default"
    language: str = "en"
    parent_ids: list[str] = Field(default_factory=list)


class SpeechSynthesisTool(Tool[SpeechInput, Artifact]):
    name = "audio.synthesize"
    description = "Synthesize narration audio with word timings and store it as an AUDIO artifact."
    input_model = SpeechInput
    output_model = Artifact
    permissions = frozenset({"media:generate", "artifact:write"})

    def __init__(self, provider: TTSProvider, artifacts: ArtifactService) -> None:
        self._provider = provider
        self._artifacts = artifacts

    async def run(self, data: SpeechInput, scope: ExecutionScope) -> Artifact:
        audio = await self._provider.synthesize(data.text, data.voice, data.language)
        return self._artifacts.store(
            task_id=_require_task(scope), name=data.name, type=ArtifactType.AUDIO, media_type=audio.media_type,
            content=audio.content, provider=audio.provider, parent_ids=data.parent_ids,
            metadata={"duration_ms": audio.duration_ms, "timings": [t.model_dump() for t in audio.timings]},
            scope=scope,
        )


class VideoInput(Schema):
    name: str
    scenes: list[SceneSpec] = Field(min_length=1)
    parent_ids: list[str] = Field(default_factory=list)


class VideoRenderTool(Tool[VideoInput, Artifact]):
    name = "video.render"
    description = "Render scenes into a video and store it as a VIDEO artifact."
    input_model = VideoInput
    output_model = Artifact
    permissions = frozenset({"media:generate", "artifact:write"})
    timeout_seconds = 600.0

    def __init__(self, provider: VideoProvider, artifacts: ArtifactService) -> None:
        self._provider = provider
        self._artifacts = artifacts

    async def run(self, data: VideoInput, scope: ExecutionScope) -> Artifact:
        video = await self._provider.render(data.scenes)
        return self._artifacts.store(
            task_id=_require_task(scope), name=data.name, type=ArtifactType.VIDEO, media_type=video.media_type,
            content=video.content, provider=video.provider, parent_ids=data.parent_ids,
            metadata={**video.metadata, "duration_ms": video.duration_ms}, scope=scope,
        )
